language: python
python:
  - 2.7

install:
  - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
  - python bootstrap.py --version 1.6.0
  - bin/buildout

script:
  - ./pre-commit-check.sh
 
notifications:
  irc:
    - "irc.freenode.org#sprint"
  email:
    - nejc.zupan@gmail.com
